### ISSUE TITLE
Configurable trigram limit

### ISSUE THREAD

**Issue by BlakeMScurr** [hypermodeinc/dgraph#2427]
It would be nice to be able to configure the max trigram limit by a flag or something rather than it being hardcoded to 1M, as discuessed here https://discuss.dgraph.io/t/checking-capitalisation-with-regex/2314/3?u=blakemscurr

It's particularly important for us since we give users the ability to write their own regex that is ultimately run through dgraph, so we can't know the correct limit ahead of time.

**Comment by manishrjain** [comment]
If you'd like to send a PR to remove that limit, I could accept it.

**Comment by BlakeMScurr** [comment]
@manishrjain Here's that flag :smile: it works, but I could easily be missing some subtlety.
