### ISSUE TITLE
Abnormal shutdown of PC, dgraph is not restarting after crash.

### ISSUE THREAD

**Issue by AJAviJain** [hypermodeinc/dgraph#2573]
2018/09/07 11:48:19 Error while creating badger KV WAL store error: CreateFileMapping: The volume for a file has been externally altered so that the opened file is no longer valid.
Unable to map file
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.Wrapf
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/error.go:82
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table.OpenTable
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/table/table.go:136
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.newLevelsController
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:118
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:271
github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage
        /ext-go/1/src/github.com/dgraph-io/dgraph/edgraph/server.go:111
github.com/dgraph-io/dgraph/edgraph.InitServerState
        /ext-go/1/src/github.com/dgraph-io/dgraph/edgraph/server.go:67
github.com/dgraph-io/dgraph/dgraph/cmd/server.run
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:314
github.com/dgraph-io/dgraph/dgraph/cmd/server.init.0.func1
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:54
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:46
main.main
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:24
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
Opening table: "E:\\Softwares\\DGraph\\var\\w\\000323.sst"
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.newLevelsController
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/levels.go:121
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:271
github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage
        /ext-go/1/src/github.com/dgraph-io/dgraph/edgraph/server.go:111
github.com/dgraph-io/dgraph/edgraph.InitServerState
        /ext-go/1/src/github.com/dgraph-io/dgraph/edgraph/server.go:67
github.com/dgraph-io/dgraph/dgraph/cmd/server.run
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:314
github.com/dgraph-io/dgraph/dgraph/cmd/server.init.0.func1
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/server/run.go:54
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:46
main.main
        /ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:24
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361

**Comment by AJAviJain** [comment]
Version - v1.0.8 and Windows 16GB RAM.

I have tried deleting lock files, also tried deleting the empty sst files in directories.

It has got crashed while i was using version v1.0.8_rc1 so i have tried restarting with latest version, but the error is same.

zero have got started after deleting lock file, but dgraph server is not getting start, you can check the above logs i am getting while running dgraph.

**Comment by manishrjain** [comment]
Deleting lock file is ok. But, deleting SST file is not.

Can you run `badger info` tool on the p directory? You can compile it from Badger code.
